M48
; DRILL file {KiCad 7.0.10} date Tue Apr  9 17:15:32 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-09T17:15:32+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0472
%
G90
G05
T1
X0.85Y-1.15
X1.05Y-1.15
T2
X0.85Y-1.55
X1.45Y-1.55
T3
X1.45Y-1.15
X1.45Y-1.25
X1.75Y-1.15
X1.75Y-1.25
T4
X1.15Y-0.85
X1.35Y-0.85
M30
